# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from PyQt5.QtWidgets import QTableWidgetItem
from PyQt5.QtGui import QIcon
from matplotlib.figure import Figure
from datetime import date
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd
import yfinance as yf
import pandas_datareader.data as pdr
import os,sys
import sqlite3
from imports import RSI,MACD,EMA
yf.pdr_override()

class Ui_add_window(object):
    
    def add_db(self,text,quantity):
        db_path = os.path.join(os.path.dirname(sys.argv[0]), "Stock_data.db")
        db = sqlite3.connect(str(db_path))
        cursor = db.cursor()
        data = yf.Ticker(text).info
        price = str(data['currentPrice'])
        if quantity == "":    
            pass
        else:
            data1 = (str(date.today()),text,"Buy",quantity,price,float(quantity) * float(price))
            
            command = "INSERT INTO Stock VALUES(?,?,?,?,?,?)"
            
            cursor.execute(command,data1)
            
            db.commit()
        db.close()
        
        
    def Stock_press(self,text):
        self.Chart.setText(text)
        data = yf.Ticker(text).info
        
        price = str(data['currentPrice'])
        open_ = str(data['open'])
        high = str(data['dayHigh'])
        low = str(data['dayLow'])
        close = str(data['previousClose'])
        
        
        db_path = os.path.join(os.path.dirname(sys.argv[0]), "Stock_data.db")
        con = sqlite3.connect(str(db_path))
        query = ''' Select * from Stock '''
        df = pd.read_sql_query(query, con)
        con.close()
        
        
        contains_text = df['Name'].str.contains(text)
        filtered_df = df[contains_text]
        if not filtered_df.empty:
            quant = str(filtered_df['Quantity'].sum())
            tot_amnt = filtered_df['Amount'].sum()
            rounded_amount = round(tot_amnt, 2)
            rounded_amount_str = "{:.2f}".format(rounded_amount)
            self.Current_holding.setText(quant)
            self.Tot_inv.setText(rounded_amount_str)
        else:
            quant = str(0)
            self.Current_holding.setText(quant)
            self.Tot_inv.setText(quant)
        
        
        
        
        self.Curr_price.setText(price)
        self.Open.setText(open_)
        self.High.setText(high)
        self.Low.setText(low)
        self.Close.setText(close)
        
        
        df = pdr.get_data_yahoo(text,start='2023-01-01',end = date.today())
        
        self.figure_chart.clear()
        axes = self.figure_chart.add_subplot(111)
        axes.plot(df.Close)
        axes.set_xlabel('Date')
        axes.set_ylabel('Closing Price')
        self.canvas.draw()
        
        
        self.figure_RSI.clear()
        axes = self.figure_RSI.add_subplot(111)
        x,y = RSI(text)
        axes.plot(x,y,color='lightgray')
        axes.set_xlabel('Date',color='white')
        axes.set_ylabel('Strength',color='white')
        axes.axhline(0,linestyle='--',alpha=0.5,color='#ff0000')
        axes.axhline(30,linestyle='--',alpha=0.5,color='#cccccc')
        axes.axhline(70,linestyle='--',alpha=0.5,color='#cccccc')
        axes.axhline(100,linestyle='--',alpha=0.5,color='#ff0000')
        axes.set_title('RSI Value')
        axes.grid(False)
        axes.set_axisbelow(True)
        axes.set_facecolor('black')
        axes.figure.set_facecolor('#121212')
        date_format = mdates.DateFormatter('%d')
        axes.xaxis.set_major_locator(mdates.MonthLocator(interval=1))
        axes.tick_params(axis='x',colors='white',labelsize=8)
        axes.tick_params(axis='y',colors='white')
        self.canvas_RSI.draw()
        
        
        
        self.figure_EMA.clear()
        axes = self.figure_EMA.add_subplot(111)
        x,e12,e24,e55 = EMA(text)
        axes.plot(x,e12,color='red',label='12-EMA')
        axes.plot(x,e24,color='lightblue',label='24-EMA')
        axes.plot(x,e55,color='green',label='55-EMA')
        axes.legend()
        axes.set_facecolor('black')
        axes.figure.set_facecolor('#121212')
        axes.set_title('EMA 12-24-55')
        axes.tick_params(axis='x',colors='white',labelsize=8)
        axes.tick_params(axis='y',colors='white')
        self.canvas_EMA.draw()
        
        
        self.figure_MACD.clear()
        axes = self.figure_MACD.add_subplot(111)
        x,macd,sig= MACD(text)
        
        
        if macd[-1] <= sig[-1]:
            self.sugg_text.setText("Wait for MACD Reversal")
        else:
            self.sugg_text.setText("Safe to buy")
            
        
        axes.plot(x,macd,color='green',label='MACD')
        axes.plot(x,sig,color='red',label='Signal')
        axes.legend()
        axes.set_facecolor('black')
        axes.figure.set_facecolor('#121212')
        axes.set_title('MACD')
        axes.tick_params(axis='x',colors='white',labelsize=8)
        axes.tick_params(axis='y',colors='white')
        self.canvas_MACD.draw()
        
        
        
    
    def setupUi(self, add_window):
        add_window.setObjectName("add_window")
        add_window.resize(905, 959)
        add_window.setWindowIcon(QIcon('add.png'))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(add_window.sizePolicy().hasHeightForWidth())
        add_window.setSizePolicy(sizePolicy)
        add_window.setMinimumSize(QtCore.QSize(905, 959))
        add_window.setMaximumSize(QtCore.QSize(905, 959))
        add_window.setStyleSheet("color: rgb(0, 0, 128);\n"
"background-color: rgb(211, 211, 211);")
        
        self.Stock = QtWidgets.QLabel(add_window)
        self.Stock.setGeometry(QtCore.QRect(-30, 10, 161, 41))
        self.Stock.setAutoFillBackground(False)
        self.Stock.setAlignment(QtCore.Qt.AlignCenter)
        self.Stock.setObjectName("Stock")
        self.Stock_name = QtWidgets.QLineEdit(add_window)
        self.Stock_name.setGeometry(QtCore.QRect(110, 10, 611, 51))
        self.Stock_name.setStyleSheet("color: rgb(0, 0, 128);\n"
"background-color: rgb(125, 153, 126);")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.Stock_name.setFont(font)
        self.Stock_name.setAutoFillBackground(False)
        self.Stock_name.setText("")
        self.Stock_name.setAlignment(QtCore.Qt.AlignCenter)
        self.Stock_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_name.setObjectName("Stock_name")
        
        self.Submit = QtWidgets.QPushButton(add_window,clicked = lambda: self.Stock_press(self.Stock_name.text()))
        self.Submit.setGeometry(QtCore.QRect(730, 10, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Submit.setFont(font)
        self.Submit.setObjectName("Submit")
        self.label_2 = QtWidgets.QLabel(add_window)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Current_holding = QtWidgets.QLineEdit(add_window)
        self.Current_holding.setStyleSheet("color: rgb(0, 0, 128);\n"
"background-color: rgb(125, 153, 126);")
        self.Current_holding.setGeometry(QtCore.QRect(260, 70, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Current_holding.setFont(font)
        self.Current_holding.setText("")
        self.Current_holding.setObjectName("Current_holding")
        self.label_3 = QtWidgets.QLabel(add_window)
        self.label_3.setGeometry(QtCore.QRect(70, 140, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.Curr_price = QtWidgets.QLineEdit(add_window)
        self.Curr_price.setGeometry(QtCore.QRect(472, 140, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Curr_price.setFont(font)
        self.Curr_price.setAlignment(QtCore.Qt.AlignCenter)
        self.Curr_price.setObjectName("Curr_price")
        self.Curr_price.setStyleSheet("color: rgb(0, 0, 128);\n"
"background-color: rgb(125, 153, 126);")
        self.label_4 = QtWidgets.QLabel(add_window)
        self.label_4.setGeometry(QtCore.QRect(-10, 200, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.Open = QtWidgets.QLineEdit(add_window)
        self.Open.setGeometry(QtCore.QRect(80, 200, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Open.setFont(font)
        self.Open.setText("")
        self.Open.setStyleSheet("color: rgb(0, 0, 128);\n"
"background-color: rgb(125, 153, 126);")
        self.Open.setAlignment(QtCore.Qt.AlignCenter)
        self.Open.setObjectName("Open")
        
        self.High = QtWidgets.QLineEdit(add_window)
        self.High.setGeometry(QtCore.QRect(300, 200, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.High.setStyleSheet("color: rgb(0, 0, 128);\n"
"background-color: rgb(125, 153, 126);")
        self.High.setFont(font)
        self.High.setAlignment(QtCore.Qt.AlignCenter)
        self.High.setObjectName("High")
        
        
        
        self.label_5 = QtWidgets.QLabel(add_window)
        self.label_5.setGeometry(QtCore.QRect(220, 201, 80, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.Low = QtWidgets.QLineEdit(add_window)
        self.Low.setGeometry(QtCore.QRect(530, 200, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Low.setFont(font)
        self.Low.setAlignment(QtCore.Qt.AlignCenter)
        self.Low.setObjectName("Low")
        self.Low.setStyleSheet("color: rgb(0, 0, 128);\n"
"background-color: rgb(125, 153, 126);")
        self.label_6 = QtWidgets.QLabel(add_window)
        self.label_6.setGeometry(QtCore.QRect(444, 201, 80, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.Close = QtWidgets.QLineEdit(add_window)
        self.Close.setStyleSheet("color: rgb(0, 0, 128);\n"
"background-color: rgb(125, 153, 126);")
        self.Close.setGeometry(QtCore.QRect(750, 200, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Close.setFont(font)
        self.Close.setAlignment(QtCore.Qt.AlignCenter)
        self.Close.setObjectName("Close")
        self.label_7 = QtWidgets.QLabel(add_window)
        self.label_7.setGeometry(QtCore.QRect(670, 201, 80, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.Chart = QtWidgets.QLabel(add_window)
        self.Chart.setGeometry(QtCore.QRect(20, 260, 811, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Chart.setFont(font)
        self.Chart.setAlignment(QtCore.Qt.AlignCenter)
        self.Chart.setObjectName("Chart")
        
        
        
        self.graphicsView = QtWidgets.QGraphicsView(add_window)
        self.graphicsView.setGeometry(QtCore.QRect(15, 300, 871, 261))
        self.graphicsView.setStyleSheet("color: rgb(0, 0, 128);\n"
"background-color: rgb(211, 211, 211);")
        self.graphicsView.setObjectName("graphicsView")
        self.figure_chart = Figure(figsize=(8.5, 2.5))
        self.canvas = FigureCanvas(self.figure_chart)
        self.scene = QtWidgets.QGraphicsScene(self.graphicsView)
        self.scene.addWidget(self.canvas)
        self.graphicsView.setScene(self.scene)
        
        
        
        self.Suggestion = QtWidgets.QLabel(add_window)
        self.Suggestion.setGeometry(QtCore.QRect(50, 570, 811, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Suggestion.setFont(font)
        self.Suggestion.setAlignment(QtCore.Qt.AlignCenter)
        self.Suggestion.setObjectName("Suggestion")
        
        self.Add_but = QtWidgets.QPushButton(add_window,clicked = lambda : self.add_db(self.Stock_name.text(),self.lineEdit.text()))
        self.Add_but.setGeometry(QtCore.QRect(640, 880, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Add_but.setFont(font)
        self.Add_but.setObjectName("Add_but")
        
        self.label = QtWidgets.QLabel(add_window)
        
        self.label.setGeometry(QtCore.QRect(100, 890, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setMidLineWidth(-3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        self.lineEdit = QtWidgets.QLineEdit(add_window)
        self.lineEdit.setStyleSheet("color: rgb(0, 0, 128);\n"
"background-color: rgb(125, 153, 126);")
        font.setBold(False)
        font.setWeight(50)
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        
        self.lineEdit.setGeometry(QtCore.QRect(270, 890, 113, 45))
        self.lineEdit.setObjectName("lineEdit")
        
        self.Tot_inv_lab = QtWidgets.QLabel(add_window)
        self.Tot_inv_lab.setGeometry(QtCore.QRect(490, 80, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Tot_inv_lab.setFont(font)
        self.Tot_inv_lab.setObjectName("Tot_inv_lab")
        
        self.Tot_inv = QtWidgets.QLineEdit(add_window)
        self.Tot_inv.setGeometry(QtCore.QRect(640, 70, 191, 41))
        font = QtGui.QFont()
        self.Tot_inv.setStyleSheet("color: rgb(0, 0, 128);\n"
"background-color: rgb(125, 153, 126);")
        font.setPointSize(16)
        self.Tot_inv.setFont(font)
        self.Tot_inv.setAlignment(QtCore.Qt.AlignCenter)
        self.Tot_inv.setObjectName("Tot_inv")
        
        self.tabWidget = QtWidgets.QTabWidget(add_window)
        self.tabWidget.setGeometry(QtCore.QRect(20, 600, 871, 251))
        self.tabWidget.setObjectName("tabWidget")
        
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.sugg_text = QtWidgets.QLineEdit(self.tab_4)
        self.sugg_text.setGeometry(QtCore.QRect(0, 0, 871, 221))
        self.sugg_text.setObjectName("sugg_text")
        font = QtGui.QFont()
        font.setPointSize(40)
        self.sugg_text.setAlignment(QtCore.Qt.AlignCenter)
        self.sugg_text.setFont(font)
        
        self.tabWidget.addTab(self.tab_4, "")
        
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.SMA_20_200 = QtWidgets.QGraphicsView(self.tab)
        self.SMA_20_200.setGeometry(QtCore.QRect(0, 0, 871, 221))
        self.SMA_20_200.setObjectName("SMA_20_200")
        self.figure_EMA = Figure(figsize=(8.5,2))
        self.canvas_EMA = FigureCanvas(self.figure_EMA)
        self.scene_EMA = QtWidgets.QGraphicsScene(self.SMA_20_200)
        self.scene_EMA.addWidget(self.canvas_EMA)
        self.SMA_20_200.setScene(self.scene_EMA)
        self.tabWidget.addTab(self.tab, "")
        
        
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.RSI = QtWidgets.QGraphicsView(self.tab_2)
        self.RSI.setGeometry(QtCore.QRect(0, 0, 871, 221))
        self.RSI.setObjectName("RSI")
        self.figure_RSI = Figure(figsize=(8.5,2))
        self.canvas_RSI = FigureCanvas(self.figure_RSI)
        self.scene_RSI = QtWidgets.QGraphicsScene(self.RSI)
        self.scene_RSI.addWidget(self.canvas_RSI)
        self.RSI.setScene(self.scene_RSI)
        self.tabWidget.addTab(self.tab_2, "")
        
        
        
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.MACD = QtWidgets.QGraphicsView(self.tab_3)
        self.MACD.setGeometry(QtCore.QRect(0, 0, 871, 221))
        self.MACD.setObjectName("MACD")
        self.figure_MACD = Figure(figsize=(8.5,2))
        self.canvas_MACD = FigureCanvas(self.figure_MACD)
        self.scene_MACD = QtWidgets.QGraphicsScene(self.MACD)
        self.scene_MACD.addWidget(self.canvas_MACD)
        self.MACD.setScene(self.scene_MACD)
        self.tabWidget.addTab(self.tab_3, "")

        self.Add_but.clicked.connect(add_window.close)        

        self.retranslateUi(add_window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(add_window)

    def retranslateUi(self, add_window):
        _translate = QtCore.QCoreApplication.translate
        add_window.setWindowTitle(_translate("add_window", "Stock Info"))
        self.Stock.setText(_translate("add_window", "<html><head/><body><p><span style=\" font-size:18pt;\">Stock</span></p></body></html>"))
        self.Submit.setText(_translate("add_window", "Submit"))
        self.label_2.setText(_translate("add_window", "Current Holding"))
        self.label_3.setText(_translate("add_window", "Current Price"))
        self.label_4.setText(_translate("add_window", "Open"))
        self.label_5.setText(_translate("add_window", "High"))
        self.label_6.setText(_translate("add_window", "Low"))
        self.label_7.setText(_translate("add_window", "Close"))
        self.Chart.setText(_translate("add_window", "Chart"))
        self.Suggestion.setText(_translate("add_window", "Suggestion"))
        self.Add_but.setText(_translate("add_window", "ADD"))
        self.label.setText(_translate("add_window", "Quantity"))
        self.Tot_inv_lab.setText(_translate("add_window", "Total Inv."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("add_window", "Suggestion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("add_window", "EMA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("add_window", "RSI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("add_window", "MACD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_window = QtWidgets.QDialog()
    ui = Ui_add_window()
    ui.setupUi(add_window)
    add_window.show()
    sys.exit(app.exec_())
