# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chart.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from PyQt5.QtGui import QIcon
from matplotlib.figure import Figure
import pandas_datareader.data as pdr
import yfinance as yf
yf.pdr_override()
import matplotlib.pyplot as plt
from PyQt5.QtCore import QDate
import sys


class Ui_Chart(object):
    
    def display(self,text,sdate,edate):
        sdate = sdate.toString("yyyy-MM-dd")
        edate = edate.toString("yyyy-MM-dd")
        df = pdr.get_data_yahoo(text,start=sdate,end=edate)
        
        self.figure.clear()
        axes = self.figure.add_subplot(111)
        axes.set_position([0.075, 0.099, 0.9, 0.9])
        axes.tick_params(axis='x',labelsize=13)
        axes.tick_params(axis='y',labelsize=15)
        axes.plot(df.Close)
        axes.set_xlabel('Date',fontsize=12)
        axes.set_ylabel('Closing Price',fontsize=22)
        self.canvas.draw()
    
    def setupUi(self, Chart):
        Chart.setObjectName("Chart")
        Chart.resize(1309, 760)
        Chart.setWindowIcon(QIcon('chart.png'))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Chart.sizePolicy().hasHeightForWidth())
        Chart.setSizePolicy(sizePolicy)
        Chart.setMinimumSize(QtCore.QSize(1309, 759))
        Chart.setMaximumSize(QtCore.QSize(1309, 761))
        Chart.setStyleSheet("color: rgb(60, 255, 73);\n"
"background-color: rgb(211, 211, 211);")
        self.Stock_name = QtWidgets.QLabel(Chart)
        self.Stock_name.setGeometry(QtCore.QRect(190, 20, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Stock_name.setFont(font)
        self.Stock_name.setStyleSheet("color: rgb(60, 255, 73);\n"
"background-color: rgb(125, 153, 126);")
        self.Stock_name.setAlignment(QtCore.Qt.AlignCenter)
        self.Stock_name.setObjectName("Stock_name")
        self.name = QtWidgets.QLineEdit(Chart)
        self.name.setGeometry(QtCore.QRect(430, 20, 521, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name.setFont(font)
        self.name.setStyleSheet("color: rgb(0, 0, 128);\n"
"")
        self.name.setText("")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.sub_but = QtWidgets.QPushButton(Chart,clicked = lambda: self.display(self.name.text(),self.Date.date(), self.End_date.date()))
        self.sub_but.setGeometry(QtCore.QRect(1030, 20, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sub_but.setFont(font)
        self.sub_but.setStyleSheet("color: rgb(60, 255, 73);\n"
"background-color: rgb(125, 153, 126);")
        self.sub_but.setObjectName("sub_but")
        self.label = QtWidgets.QLabel(Chart)
        self.label.setGeometry(QtCore.QRect(-10, 170, 1381, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(60, 255, 73);\n"
"background-color: rgb(125, 153, 126);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        self.Graph = QtWidgets.QGraphicsView(Chart)
        self.Graph.setGeometry(QtCore.QRect(10, 250, 1291, 495))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Graph.sizePolicy().hasHeightForWidth())
        self.Graph.setSizePolicy(sizePolicy)
        self.Graph.setMinimumSize(QtCore.QSize(1291, 495))
        self.Graph.setMaximumSize(QtCore.QSize(1291, 495))
        self.Graph.setObjectName("Graph")
        self.figure = Figure(figsize=(12.8, 4.8))
        self.canvas = FigureCanvas(self.figure)
        self.scene = QtWidgets.QGraphicsScene(self.Graph)
        self.scene.addWidget(self.canvas)
        self.Graph.setScene(self.scene)
        
        self.Date = QtWidgets.QDateEdit(Chart)
        self.Date.setGeometry(QtCore.QRect(260, 100, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Date.setFont(font)
        self.Date.setStyleSheet("color: rgb(0, 0, 128);")
        self.Date.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.Date.setObjectName("Date")
        
        self.End_date = QtWidgets.QDateEdit(Chart)
        self.End_date.setGeometry(QtCore.QRect(1080, 100, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.End_date.setFont(font)
        self.End_date.setStyleSheet("color: rgb(0, 0, 128);")
        self.End_date.setObjectName("End_date")
        self.label_2 = QtWidgets.QLabel(Chart)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(60, 255, 73);\n"
"background-color: rgb(125, 153, 126);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Chart)
        self.label_3.setGeometry(QtCore.QRect(870, 100, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(60, 255, 73);\n"
"background-color: rgb(125, 153, 126);\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Chart)
        QtCore.QMetaObject.connectSlotsByName(Chart)

    def retranslateUi(self, Chart):
        _translate = QtCore.QCoreApplication.translate
        Chart.setWindowTitle(_translate("Chart", "Chart"))
        self.Stock_name.setText(_translate("Chart", "Stock Name"))
        self.sub_but.setText(_translate("Chart", "Submit"))
        self.label.setText(_translate("Chart", "Chart"))
        self.label_2.setText(_translate("Chart", "Start Date"))
        self.label_3.setText(_translate("Chart", "End Date"))


if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    Chart = QtWidgets.QDialog()
    ui = Ui_Chart()
    ui.setupUi(Chart)
    Chart.show()
    sys.exit(app.exec_())
