# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Short.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import sys
import pandas as pd
import os
import sqlite3
from datetime import  date
from PyQt5.QtWidgets import QTableWidgetItem
import yfinance as yf
from imports import MACD

stock_quant = 0

class Ui_SELL(object):
    
    def display(self,text):
        db_path = os.path.join(os.path.dirname(sys.argv[0]), "Stock_data.db")
        db = sqlite3.connect(str(db_path))
        cursor = db.cursor()
        
        query = '''SELECT * FROM STOCK '''
        
        df = pd.read_sql_query(query,db)
        
        df = df[df.Name == text]
        
        df.drop(['Name','Price'],axis=1,inplace=True)
        df['Quantity'] = pd.to_numeric(df['Quantity'])
        df['Amount'] = pd.to_numeric(df['Amount'])
        
        x,macd,sig = MACD(text)
        if macd[-1] <= sig[-1]:
            self.Sugg_disp.setText("Sell")
        else:
            self.Sugg_disp.setText("Hold")

        self.Table.setColumnCount(df.shape[1])
        self.Table.setRowCount(df.shape[0])
        
        for i, row in enumerate(df.values):
            for j, value in enumerate(row):
                item = QTableWidgetItem(str(value))
                self.Table.setItem(i, j, item)
        
        global stock_quant
        stock_quant = df['Quantity'].sum()
        
        self.Quant_disp.setText("")
        self.Quant_disp.setText(str(stock_quant))
        
        cursor.close()
        db.close()
        
    def sell(self,text,quant):
        if int(stock_quant) >= int(quant):
            df = yf.Ticker(text).info
            price = str(df['currentPrice'])
            data = {'Date' : date.today() , 'Name' : text , 'Action' : 'Sell' , 'Quantity': -int(quant),
                    'Price' : price, 'Amount' : -int(quant)*float(price)}
            new_df = pd.DataFrame([data])
            
            
            
            db_path = os.path.join(os.path.dirname(sys.argv[0]), "Stock_data.db")
            db = sqlite3.connect(str(db_path))
            cursor = db.cursor()
            query = '''SELECT * FROM STOCK '''
            
            df = pd.read_sql_query(query,db)
            df['Quantity'] = pd.to_numeric(df['Quantity'])
            df['Amount'] = pd.to_numeric(df['Amount'])
            df = df[df.Name == text]
            
            PL = float(price) - float(df['Amount'].sum()) / float(df['Quantity'].sum())
            PL = float(PL) * int(quant)
            PL = round(PL , 2)
            
            self.PL_disp.setText(str(PL))
            new_df.to_sql('Stock', db, if_exists='append', index=False)
            
        
            cursor.close()
            db.close()
    
    
    
    def setupUi(self, SELL):
        SELL.setObjectName("SELL")
        SELL.resize(931, 735)
        SELL.setStyleSheet("background-color: rgb(123, 123, 123);\n"
"")
        SELL.setWindowIcon(QIcon('sell.png'))
        self.stock = QtWidgets.QLabel(SELL)
        self.stock.setGeometry(QtCore.QRect(30, 20, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.stock.setFont(font)
        self.stock.setStyleSheet("background-color: rgb(210, 210, 220);")
        self.stock.setAlignment(QtCore.Qt.AlignCenter)
        self.stock.setObjectName("stock")
        self.stock_name = QtWidgets.QLineEdit(SELL)
        self.stock_name.setGeometry(QtCore.QRect(230, 20, 451, 41))
        self.stock_name.setStyleSheet("background-color: rgb(125, 153, 126);")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stock_name.setFont(font)
        self.stock_name.setStyleSheet("font: 15pt \"MS Shell Dlg 2\" rgb(34, 226, 255);\n""background-color: rgb(125, 153, 126);")
        self.stock_name.setText("")
        self.stock_name.setObjectName("stock_name")
        self.sub_but = QtWidgets.QPushButton(SELL,clicked = lambda: self.display(self.stock_name.text()))
                                                                            
        self.sub_but.setGeometry(QtCore.QRect(710, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sub_but.setFont(font)
        self.sub_but.setStyleSheet("background-color: rgb(210, 210, 220);")
        self.sub_but.setObjectName("sub_but")
        self.Clo_but = QtWidgets.QPushButton(SELL)
        self.Clo_but.setGeometry(QtCore.QRect(720, 650, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Clo_but.setFont(font)
        self.Clo_but.setStyleSheet("background-color: rgb(210, 210, 220);")
        self.Clo_but.setObjectName("Clo_but")
        self.Clo_but.clicked.connect(SELL.close) 
        
        self.Table = QtWidgets.QTableWidget(SELL)
        self.Table.setGeometry(QtCore.QRect(25, 80, 601, 631))
        self.Table.setStyleSheet("font: 15pt \"MS Shell Dlg 2\" ;\n"
"background-color: rgb(200, 210, 200);\n"
"")
        self.Table.setObjectName("Table")
        self.Table.setColumnCount(4)
        self.Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(3, item)
        self.Table.horizontalHeader().setDefaultSectionSize(149)
        
        self.Sugg = QtWidgets.QLabel(SELL)
        self.Sugg.setGeometry(QtCore.QRect(680, 80, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Sugg.setFont(font)
        self.Sugg.setStyleSheet("background-color: rgb(210, 210, 220);")
        self.Sugg.setAlignment(QtCore.Qt.AlignCenter)
        self.Sugg.setObjectName("Sugg")
        self.Sugg_disp = QtWidgets.QLabel(SELL)
        self.Sugg_disp.setGeometry(QtCore.QRect(690, 140, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Sugg_disp.setFont(font)
        self.Sugg_disp.setStyleSheet("background-color: rgb(125, 153, 126);\n"
"")
        
        self.Sugg_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.Sugg_disp.setObjectName("Sugg_disp")
        self.Quant = QtWidgets.QLabel(SELL)
        self.Quant.setGeometry(QtCore.QRect(694, 205, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Quant.setFont(font)
        self.Quant.setStyleSheet("background-color: rgb(210, 210, 220);")
        self.Quant.setAlignment(QtCore.Qt.AlignCenter)
        self.Quant.setObjectName("Quant")
        self.Quant_disp = QtWidgets.QLabel(SELL)
        self.Quant_disp.setGeometry(QtCore.QRect(690, 260, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Quant_disp.setFont(font)
        self.Quant_disp.setStyleSheet("background-color: rgb(125, 153, 126);\n"
"")
        self.Quant_disp.setText("")
        self.Quant_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.Quant_disp.setObjectName("Quant_disp")
        self.Sell = QtWidgets.QLabel(SELL)
        self.Sell.setGeometry(QtCore.QRect(640, 370, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Sell.setFont(font)
        self.Sell.setStyleSheet("background-color: rgb(210, 210, 220);")
        self.Sell.setAlignment(QtCore.Qt.AlignCenter)
        self.Sell.setObjectName("Sell")
        self.Sell_disp = QtWidgets.QLineEdit(SELL)
        self.Sell_disp.setGeometry(QtCore.QRect(720, 370, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Sell_disp.setFont(font)
        self.Sell_disp.setObjectName("Sell_disp")
        self.PL = QtWidgets.QLabel(SELL)
        self.PL.setGeometry(QtCore.QRect(700, 455, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.PL.setFont(font)
        self.PL.setStyleSheet("background-color: rgb(210, 210, 220);")
        self.PL.setAlignment(QtCore.Qt.AlignCenter)
        self.PL.setObjectName("PL")
        self.PL_disp = QtWidgets.QLabel(SELL)
        self.PL_disp.setGeometry(QtCore.QRect(700, 510, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.PL_disp.setFont(font)
        self.PL_disp.setStyleSheet("background-color: rgb(125, 153, 126);\n"
"")
        self.PL_disp.setText("")
        self.PL_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.PL_disp.setObjectName("PL_disp")
        self.sell_sub_but = QtWidgets.QPushButton(SELL,clicked = lambda: self.sell(self.stock_name.text(),self.Sell_disp.text()))
        self.sell_sub_but.setGeometry(QtCore.QRect(830, 370, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sell_sub_but.setFont(font)
        self.sell_sub_but.setStyleSheet("background-color: rgb(210, 210, 220);")
        self.sell_sub_but.setObjectName("sell_sub_but")

        self.retranslateUi(SELL)
        QtCore.QMetaObject.connectSlotsByName(SELL)

    def retranslateUi(self, SELL):
        _translate = QtCore.QCoreApplication.translate
        SELL.setWindowTitle(_translate("SELL", "Short"))
        self.stock.setText(_translate("SELL", "Stock Name"))
        self.sub_but.setText(_translate("SELL", "Submit"))
        self.Clo_but.setText(_translate("SELL", "Close"))
        item = self.Table.horizontalHeaderItem(0)
        item.setText(_translate("SELL", "Date"))
        item = self.Table.horizontalHeaderItem(1)
        item.setText(_translate("SELL", "Action"))
        item = self.Table.horizontalHeaderItem(2)
        item.setText(_translate("SELL", "Quantity"))
        item = self.Table.horizontalHeaderItem(3)
        item.setText(_translate("SELL", "Amount"))
        self.Sugg.setText(_translate("SELL", "Suggestion"))
        self.Quant.setText(_translate("SELL", "Quantity"))
        self.Sell.setText(_translate("SELL", "Sell"))
        self.PL.setText(_translate("SELL", "Profit / Loss"))
        self.sell_sub_but.setText(_translate("SELL", "Submit"))


if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    SELL = QtWidgets.QDialog()
    ui = Ui_SELL()
    ui.setupUi(SELL)
    SELL.show()
    sys.exit(app.exec_())
